# -*- coding: utf-8 -*-
"""MLtest1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KchD-m6cBFrzfu8SRxLVKOVGyPBYo19X

# **第1章 機械学習の準備**

## 03　機械学習の準備をしよう
"""

print("Hello")

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
plt.plot([0,2,1,3])
plt.show()